TrajectoryPlannerROS:
  max_vel_x: 50.0
  min_vel_x: 0.1
  max_vel_theta: 10
  min_in_place_vel_theta: 2

  acc_lim_theta: 50
  acc_lim_x: 50
  acc_lim_y: 50

  holonomic_robot: true
  meter_scoring: true
