obstacle_range: 10.0
raytrace_range: 30.0

robot_radius: 1.25

inflation_radius: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_laser, data_type: LaserScan, topic: base_scan, marking: true, clearing: true}
